---
name: sgd
loss: l1loss_with_cvvdp
cvvdp-weight: 0.05
actual-batch-size:
virtual-batch-size: 8
clip-size: 8
epochs: 50
learning-rate: 1e-4
learning-rate-gamma: 1.0
learning-rate-milestones: []
weight-decay: 1e-4
momentum: null
dropout-rate: null