---
scene_names: [CBApocalypse, FloodedGrounds, ScifiBase, ScifiFacility, SunTemple]
training-input-img-path: ../data/training_data/QRISP/*/540p
training-output-img-path: ../data/training_data/QRISP/*/540p
frame-height: 540
frame-width: 960
ground-truth-path-suffix: Enhanced
colour-path-suffix: MipBiasMinus1
depth-path-suffix: DepthMipBiasMinus1
camera-data-path-suffix: CameraData
motion-vector-path-suffix: MotionVectorsMipBiasMinus1
