---
scene_names: [CBApocalypse, FloodedGrounds, FloodedGroundsBridges, ScifiBase, ScifiBaseNightStartStop, ScifiBaseStartStop, ScifiFacility, SunTemple, SunTempleBush, SunTempleLamps]
training-input-img-path: ../data/training_data/QRISP/*/270p/MipBiasMinus2Jittered
training-output-img-path: ../data/training_data/QRISP/*/270p/Enhanced
