---
scene_names: [CBApocalypse, FloodedGrounds, FloodedGroundsBridges, ScifiBase, ScifiBaseNightStartStop, ScifiBaseStartStop, ScifiFacility, SunTemple, SunTempleBush, SunTempleLamps]
training-input-img-path: ../data/training_data/QRISP/*/540p
training-output-img-path: ../data/training_data/QRISP/*/540p
ground-truth-path-suffix: Enhanced
colour-path-suffix: MipBiasMinus1
depth-path-suffix: DepthMipBiasMinus1
camera-data-path-suffix: CameraData
motion-vector-path-suffix: MotionVectorsMipBiasMinus1
