---
scene_names: [ScifiBaseStartStop]
test-input-img-path: ../data/test_data/QRISP/TestSet/*/270p
test-output-img-path: ../data/test_data/QRISP/TestSet/*/270p
ground-truth-path-suffix: Enhanced
colour-path-suffix: MipBiasMinus2
depth-path-suffix: DepthMipBiasMinus2
camera-data-path-suffix: CameraData
motion-vector-patth-suffix: MotionVectorsMipBiasMinus2