---
  image-height: 1080
  image-width: 1920
  test-input-img-path: ../data/training_data/QRISP/FloodedGrounds/1080p/Native
  test-output-img-path: ../data/training_data/QRISP/FloodedGrounds/1080p/Enhanced