training-input-img-path: ../data/training_data/QRISP/*/540p
training-output-img-path: ../data/training_data/QRISP/*/1080p/Enhanced

input-frame-height: 540
input-frame-width: 960

output-frame-height: 1080
output-frame-width: 1920

dilation-block-size: 8

scene-names: [CBApocalypse, FloodedGrounds, FloodedGroundsBridges, ScifiBase, ScifiBaseNightStartStop, ScifiBaseStartStop, ScifiFacility, SunTemple, SunTempleBush, SunTempleLamps]
is-vr: false

camera-data-path-suffix: CameraData

colour-path-suffix: MipBiasMinus1
depth-path-suffix: DepthMipBiasMinus1
motion-vector-path-suffix: MotionVectorsMipBiasMinus1

colour-jittered-path-suffix: MipBiasMinus1Jittered
depth-jittered-path-suffix: DepthMipBiasMinus1Jittered
motion-vector-jittered-path-suffix: MotionVectorsMipBiasMinus1Jittered
