training-input-img-path: ../data/training_data/VR_mono/*/720x800
training-output-img-path: ../data/training_data/VR_mono/*/1440x1600/Enhanced

input-frame-height: 800
input-frame-width: 720

output-frame-height: 1600
output-frame-width: 1440

dilation-block-size: 8

scene-names: [FantasticVillage]
is-vr: false
dataset-from: unreal_engine

camera-data-path-suffix: CameraData

colour-path-suffix: MipBiasMinus1
depth-path-suffix: DepthMipBiasMinus1
motion-vector-path-suffix: MotionVectorsMipBiasMinus1

colour-jittered-path-suffix: MipBiasMinus1Jittered
depth-jittered-path-suffix: DepthMipBiasMinus1Jittered
motion-vector-jittered-path-suffix: MotionVectorsMipBiasMinus1Jittered
