validation-input-img-path:  ../data/test_data/VR/*/360x400
validation-output-img-path:  ../data/test_data/VR/*/1440x1600/Enhanced

input-frame-height: 400
input-frame-width: 360

output-frame-height: 1600
output-frame-width: 1440

dilation-block-size: 8

scene-names: [FantasticVillageStationary]
is-vr: true
dataset-from: unreal_engine
is-stationary-segment: true

camera-baseline: 6.4  # cm
horizontal-fov: 100.0  # degrees
vertical-fov: 105.8809

camera-data-path-suffix: CameraData

input-path-suffix: MipBiasMinus2
jittered-input-path-suffix: MipBiasMinus2Jittered

colour-path-suffix: Colour
depth-path-suffix: Depth
motion-vector-path-suffix: MotionVector