training-input-img-path: ../data/training_data/VR/*/720x800
training-output-img-path: ../data/training_data/VR/*/1440x1600/Enhanced

input-frame-height: 800
input-frame-width: 720

output-frame-height: 1600
output-frame-width: 1440

dilation-block-size: 8

scene-names: [FantasticVillage]
is-vr: true

camera-baseline: 6.4  # cm
horizontal-fov: 100.0  # degrees
vertical-fov: 105.8809

camera-data-path-suffix: CameraData

input-path-suffix: MipBiasMinus1
jittered-input-path-suffix: MipBiasMinus1Jittered

colour-path-suffix: Colour
depth-path-suffix: Depth
motion-vector-path-suffix: MotionVector
