test-input-img-path:  ../data/test_data/VRDataset/TestSet/*/540p
test-output-img-path:  ../data/test_data/VRDataset/TestSet/*/540p

input-frame-height: 1440
input-frame-width: 1600

output-frame-height: 1440
output-frame-width: 1600

dilation-block-size: 8

scene-names: [SeaPortVR]
is-vr: true
camera-baseline: 0.065  # metres
diagonal-fov: 110.0  # degrees
is-stationary-segment: false

camera-data-path-suffix: CameraData
ground-truth-path-suffix: Enhanced

colour-path-suffix: MipBiasMinus1
depth-path-suffix: DepthMipBiasMinus1
motion-vector-path-suffix: MotionVectorsMipBiasMinus1

colour-jittered-path-suffix: MipBiasMinus1Jittered
depth-jittered-path-suffix: DepthMipBiasMinus1Jittered
motion-vector-jittered-path-suffix: MotionVectorsMipBiasMinus1Jittered
