validation-input-img-path:  ../data/test_data/VR/*/720x800
validation-output-img-path:  ../data/test_data/VR/*/1440x1600/Enhanced

input-frame-height: 720
input-frame-width: 800

output-frame-height: 1440
output-frame-width: 1600

dilation-block-size: 8

scene-names: [FantasticVillage]
is-vr: true
is-stationary-segment: false

camera-baseline: 0.064  # metres
horizontal-fov: 100.0  # degrees
vertical-fov: 105.8809

input-path-suffix: MipBiasMinus1
jittered-input-path-suffix: MipBiasMinus1Jittered

colour-path-suffix: Colour
depth-path-suffix: Depth
motion-vector-path-suffix: MotionVector