---
defaults:
  - dataset: toy-test

setup:
  seed: 42
  display-name: standard_fhd
  jitter: true
  saved-models-path: ../saved/logs/runs/jitter/exp1/full_model.pt
  eval-output-path: evaluation_outputs
  tensorboard-dir: ../saved/logs/runs

model:
  hidden-channels: 64
  num-blocks: 5
  parameters: null

hydra:
  run:
    dir: hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
