---
defaults:
  - dataset: toy-test

setup:
  seed: 42
  display-name: standard_fhd  # standard_fhd, standard_hmd
  jitter: false

paths: 
  saved-models-path: ../saved/logs/runs/no-jitter/exp24/scale_model.pt
  evaluation-output-path: evaluation_outputs
  tensorboard-path: ../saved/logs/runs

model:
  hidden-channels: 64
  num-blocks: 5
  parameters: null

hydra:
  run:
    dir: hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
