defaults:
  - dataset: validation-upscale

setup:
  seed: 42
  display-name: standard_fhd  # standard_fhd, standard_hmd
  jitter: true

paths: 
  evaluation-output-path: evaluation_outputs
  tensorboard-path: ../saved/logs/runs
  saved-models-path: ../saved/models/scale_model.pt

model:
  hidden-channels: 16
  num-blocks: 1

validation:
  proxy-validation-interval: 1000
  primary-validation-interval: 100000
  padding: 32

hydra:
  run:
    dir: hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
