defaults:
  - dataset: validation-upscale-seaport

setup:
  seed: 42
  display-name: standard_fhd  # standard_fhd, standard_hmd
  jitter: true

paths: 
  checkpoints-path: run/checkpoints
  sanity-checks-output-path: run/sanity_checks_output
  evaluation-output-path: run/evaluation_outputs
  tensorboard-path: ../saved/logs/runs
  saved-models-path: ../saved/models/scale_model.pt

model:
  hidden-channels: 16
  num-blocks: 1

validation:
  padding: 0

hydra:
  run:
    dir: hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
